import pytest

from hdl_toolkit import NULL, HdlFile, parse
from hdl_toolkit.model import escape_value, split_line


@pytest.mark.parametrize(
    "value",
    ["plain", "a|b", "back\\slash", "ends with \\", "|", "\\|", ""],
)
def test_escape_round_trip(value):
    line = "|".join(["MERGE", "Obj", escape_value(value), "tail"])
    assert split_line(line) == ["MERGE", "Obj", value, "tail"]


def test_escape_rejects_newlines():
    with pytest.raises(ValueError):
        escape_value("two\nlines")


def test_none_is_empty_and_null_is_kept():
    assert escape_value(None) == ""
    assert escape_value(NULL) == "#NULL"


def test_add_uses_union_of_keys_in_order():
    hdl = HdlFile()
    block = hdl.add("Worker", [{"A": 1, "B": 2}, {"A": 3, "C": 4}])
    assert block.attributes == ["A", "B", "C"]
    assert block.records() == [
        {"A": "1", "B": "2", "C": ""},
        {"A": "3", "B": "", "C": "4"},
    ]


def test_to_text_and_parse_round_trip():
    hdl = HdlFile().set("PURGE_AFTER_LOAD", "Y")
    hdl.comments.append("generated by tests")
    hdl.add("Worker", [{"SourceSystemId": "W1", "Note": "x|y"}])
    hdl.add("PersonName", [{"SourceSystemId": "N1", "PersonId(SourceSystemId)": "W1"}])

    text = hdl.to_text()
    assert "MERGE|Worker|W1|x\\|y" in text
    assert text.startswith("COMMENT generated by tests\nSET PURGE_AFTER_LOAD Y\n")

    result = parse(text)
    assert result.issues == []
    assert result.file.object_names == ["Worker", "PersonName"]
    assert result.file.set_instructions == [("PURGE_AFTER_LOAD", "Y")]
    assert result.file.blocks[0].records() == [{"SourceSystemId": "W1", "Note": "x|y"}]


def test_parse_reports_orphan_and_unknown_lines():
    text = "MERGE|Worker|1\nMETADATA|Worker|Id\nUPSERT|Worker|2\nMERGE|Worker|3\n"
    result = parse(text)
    assert [i.line_number for i in result.issues] == [1, 3]
    assert len(result.file.blocks[0].lines) == 1


def test_parse_strips_bom_and_is_case_insensitive():
    result = parse("﻿metadata|Worker|Id\nmerge|Worker|1\n")
    assert result.issues == []
    assert result.file.blocks[0].lines[0].operation == "MERGE"
